Feature/add combine example
babel-cdm/CiMA pull request #4
Opened 2022-09-23 06:44 UTC by andreshbarrueco

2022-10-07 09:31 UTC, babel-cdm requested changes

2022-10-07 09:31 UTC, babel-cdm commented on CiMAExample/Shared/Domain/Repositories/HttpRepository.swift
> -//
why do you delete this?

2022-10-07 09:31 UTC, babel-cdm commented on CiMAExample/Shared/Presentation/Common/Coordinators/MainCoordinator/MainCoordinator.swift
> -//
why do you delete this?

2022-10-07 09:31 UTC, babel-cdm commented on CiMAExample/Shared/Presentation/Common/Coordinators/MainCoordinator/MainCoordinatorView.swift
> -//
why do you delete this?

2022-10-07 09:31 UTC, babel-cdm commented on CiMAExample/Shared/Presentation/Common/Coordinators/MainCoordinator/MainCoordinator.swift
> +        formViewModel = DependencyInjector.shared.getFormViewModel(coordiantor: self,
it was well written, you put it wrong

2022-10-07 09:31 UTC, babel-cdm commented on CiMAExample/Shared/Presentation/Common/Dependencies/DependencyInjector.swift
> +    func getPokemonListViewModel( coordinator: MainCoordinator, isCompletionRequestSelected: Bool) -> PokemonListViewModel {
Remove the space before `coodinator`

2022-10-07 09:31 UTC, babel-cdm commented on CiMAExample/Shared/Presentation/Common/Dependencies/DependencyInjector.swift
> +    func getMainViewModel( coordinator: MainCoordinator ) -> MainViewModel {
Remove the space before `coodinator`

2022-10-07 09:31 UTC, babel-cdm commented on CiMAExample/Shared/Presentation/Common/Dependencies/DependencyInjector.swift
> +    func getFormViewModel(coordiantor: MainCoordinator, delegate: FormDelegate? = nil) -> FormViewModel{
`coordinator`

2022-10-07 09:31 UTC, babel-cdm commented on CiMAExample/Shared/Presentation/Modules/Form/FormViewModel.swift
> +        let viewModel = DependencyInjector.shared.getFormViewModel(coordiantor: coordinator,
same as before

2022-10-10 07:22 UTC, andreshbarrueco commented on CiMAExample/Shared/Presentation/Common/Coordinators/MainCoordinator/MainCoordinator.swift
> +        formViewModel = DependencyInjector.shared.getFormViewModel(coordiantor: self,
dislexia ^^

2023-10-08 14:38 UTC, closed without merging